name: workflow_02

on:
  repository_dispatch:
    types:
      - trigger_workflow_event

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "Triggering Workflow_02"
